# Generated by Django 4.2.7 on 2026-05-08 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid South African phone number', regex='^(\\+27|0)[6-8][0-9]{8}$')])),
                ('company_name', models.CharField(blank=True, help_text='Optional - for business websites', max_length=200)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(help_text='Describe what you need for your website')),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under R5,000'), ('5k_to_10k', 'R5,000 - R10,000'), ('10k_to_20k', 'R10,000 - R20,000'), ('20k_to_50k', 'R20,000 - R50,000'), ('50k_plus', 'R50,000+'), ('custom', 'Custom Budget')], default='custom', max_length=20)),
                ('preferred_timeline', models.PositiveIntegerField(blank=True, help_text='Preferred completion time in days', null=True)),
                ('design_preferences', models.TextField(blank=True, help_text='Color schemes, style preferences, examples of websites you like')),
                ('has_logo', models.BooleanField(default=False, help_text='Do you have a logo?')),
                ('has_content', models.BooleanField(default=False, help_text='Do you have content ready (text, images)?')),
                ('has_domain', models.BooleanField(default=False, help_text='Do you have a domain name registered?')),
                ('features_needed', models.TextField(blank=True, help_text='Specific features needed (e.g., contact form, gallery, booking system)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('quoted', 'Quote Sent'), ('accepted', 'Quote Accepted'), ('in_progress', 'In Development'), ('testing', 'Testing Phase'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, related_name='applications', to='services.additionalservice')),
                ('website_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.websitetype')),
            ],
            options={
                'verbose_name': 'Website Application',
                'verbose_name_plural': 'Website Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_from_staff', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.websiteapplication')),
            ],
            options={
                'verbose_name': 'Application Message',
                'verbose_name_plural': 'Application Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='websiteapplication',
            index=models.Index(fields=['status', 'created_at'], name='application_status_a70a51_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteapplication',
            index=models.Index(fields=['email', 'status'], name='application_email_469e48_idx'),
        ),
    ]
