# Generated by Django 4.2.7 on 2026-06-01 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mobileapptype_alter_additionalservice_options_and_more'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.PositiveIntegerField()),
                ('icon', models.CharField(default='mobile', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='applicationmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='websiteapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='websiteapplication',
            name='application_status_a70a51_idx',
        ),
        migrations.RemoveIndex(
            model_name='websiteapplication',
            name='application_email_469e48_idx',
        ),
        migrations.RemoveField(
            model_name='websiteapplication',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='websiteapplication',
            name='application_type',
            field=models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile Application')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='design_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='features_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='has_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='has_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='has_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\+27|0)[6-8][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='preferred_timeline',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='websiteapplication',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.websitetype'),
        ),
        migrations.AddField(
            model_name='websiteapplication',
            name='mobile_app_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.mobileapptype'),
        ),
    ]
