# Generated by Django 4.2.7 on 2026-06-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_additionalservice_options_and_more'),
        ('applications', '0002_mobileapptype_alter_applicationmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteapplication',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='services.websitetype'),
        ),
    ]
