# Generated by Django 4.2.7 on 2026-06-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_mobile_apps_website_type'),
        ('applications', '0003_alter_websiteapplication_website_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteapplication',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services.websitetype'),
        ),
    ]
