# Generated by Django 4.2.7 on 2026-05-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hosting', 'Web Hosting'), ('domain', 'Domain Registration'), ('ssl', 'SSL Certificate'), ('maintenance', 'Website Maintenance'), ('seo', 'SEO Optimization'), ('content', 'Content Writing'), ('logo', 'Logo Design'), ('social', 'Social Media Integration'), ('analytics', 'Analytics Setup'), ('backup', 'Backup Service'), ('security', 'Security Monitoring'), ('support', 'Technical Support'), ('training', 'Website Training'), ('migration', 'Website Migration'), ('speed', 'Speed Optimization')], max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('once', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('features', models.TextField(blank=True, help_text='List features included, one per line')),
                ('is_required', models.BooleanField(default=False, help_text='Required for all websites')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('one_page', 'One Page Website'), ('business', 'Business/Brochure Website'), ('ecommerce', 'E-commerce Website'), ('portfolio', 'Portfolio Website'), ('blog', 'Blog/Content Website'), ('custom_app', 'Custom Web Application'), ('landing_page', 'Landing Page'), ('membership', 'Membership/Subscription Site'), ('real_estate', 'Real Estate Website'), ('restaurant', 'Restaurant/Food Website'), ('booking', 'Booking/Appointment Website'), ('educational', 'Educational/Learning Platform'), ('nonprofit', 'Non-Profit/Charity Website'), ('corporate', 'Corporate Enterprise Website'), ('marketplace', 'Online Marketplace')], max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='List key features, one per line')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated days to complete')),
                ('icon', models.CharField(default='globe', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Type',
                'verbose_name_plural': 'Website Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Package discount percentage', max_digits=5)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/recommended')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_services', models.ManyToManyField(blank=True, related_name='packages', to='services.additionalservice')),
                ('website_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.websitetype')),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
