# Generated by Django 4.2.7 on 2026-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='icon',
            field=models.CharField(default='cog', max_length=50),
        ),
    ]
