# Generated by Django 4.2.7 on 2026-06-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_additionalservice_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic_app', 'Basic Mobile App (Info App)'), ('business_app', 'Business Mobile App'), ('ecommerce_app', 'E-commerce Mobile App'), ('booking_app', 'Booking/Appointment App'), ('social_app', 'Social Networking App'), ('marketplace_app', 'Marketplace App'), ('custom_app', 'Custom Mobile Application'), ('education_app', 'Education/Learning App'), ('delivery_app', 'Delivery/Logistics App'), ('finance_app', 'Finance/Fintech App'), ('on_demand_app', 'On-Demand Service App')], max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='List key features, one per line')),
                ('min_price', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=250000, max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated days to complete')),
                ('icon', models.CharField(default='mobile-alt', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile App Type',
                'verbose_name_plural': 'Mobile App Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='additional_services',
            field=models.ManyToManyField(blank=True, to='services.additionalservice'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.websitetype'),
        ),
        migrations.AlterField(
            model_name='websitetype',
            name='estimated_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='mobile_app_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.mobileapptype'),
        ),
    ]
