# Generated by Django 4.2.7 on 2026-06-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mobileapptype_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Additional Service', 'verbose_name_plural': 'Additional Services'},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Service Package', 'verbose_name_plural': 'Service Packages'},
        ),
        migrations.AlterModelOptions(
            name='websitetype',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Website Type', 'verbose_name_plural': 'Website Types'},
        ),
    ]
